# This file is part of tcp-engine. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/tcp-engine/master/COPYRIGHT. No part of tcp-engine, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2016-2017 The developers of tcp-engine. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/tcp-engine/master/COPYRIGHT.


[workspace]
members = [
    "tcp-engine",
    "tcp-engine-abstractions",
    "tcp-engine-authentication",
    "tcp-engine-check-sum",
    "tcp-engine-collections",
    "tcp-engine-internet-protocol",
    "tcp-engine-network-endian",
    "tcp-engine-ports",
    "tcp-engine-tcp",
    "tcp-engine-tcp-domain",
    "tcp-engine-time",
]
